export async function getRandomFunFactAboutFonts(): Promise<string> {
    return funFacts[Math.floor(Math.random() * funFacts.length)]
}

const funFacts = [
    "Fonts can have a significant impact on the way we perceive information.",
    "The first metal typeface was developed in Korea in the 13th century.",
    "Serif fonts are considered more formal and traditional, while sans-serif fonts are seen as modern and casual.",
    "Typography is the art of arranging text in a visually appealing and legible manner.",
    "The term 'font' is derived from the Latin word 'fons,' meaning 'source' or 'spring'.",
    "Helvetica is one of the most widely used sans-serif typefaces, designed in 1957 by Max Miedinger.",
    "Times New Roman, created in 1931 by Stanley Morison and Victor Lardent, was designed for The Times newspaper.",
    "There are over 550,000 fonts in existence, with more being created every day.",
    "The first digital font, OCR-A, was created in 1966 for optical character recognition systems.",
    "Typefaces can be classified into five major groups: serif, sans-serif, script, decorative, and monospaced.",
    "The pangram 'The quick brown fox jumps over the lazy dog' contains every letter of the alphabet and is often used to showcase fonts.",
    "The most common font sizes are 10, 12, and 14 points.",
    "Leading, the space between lines of text, is named after the strips of lead used to separate lines in letterpress printing.",
    "Kerning is the process of adjusting the space between individual letter pairs for better visual balance.",
    "The '@' symbol, originally used for accounting, gained popularity with the advent of email and is now an integral part of digital communication.",
    "The ampersand '&' is a combination of the letters 'e' and 't', forming the Latin word 'et', meaning 'and'.",
    "Fonts can evoke emotions and create associations, such as luxury, playfulness, or professionalism.",
    "The font Comic Sans, designed in 1994 by Vincent Connare, is often criticized for its overuse and perceived informality.",
    "The typeface Futura, designed by Paul Renner in 1927, is based on geometric shapes and is considered a modern classic.",
    "Garamond, designed in the 16th century by Claude Garamond, is one of the earliest and most enduring serif typefaces.",
    "Variable fonts allow for the adjustment of multiple font attributes, such as width and weight, within a single font file.",
    "Web fonts enable the use of custom typefaces on websites, improving design consistency and accessibility.",
    "The first italic typeface was created in 1501 by Aldus Manutius, a Venetian printer, to save space and create more legible text.",
    "The font size 'point' system was established by Pierre Simon Fournier in the 18th century.",
    "Slab serif fonts, characterized by thick, block-like serifs, were popular in the 19th century for advertisements and posters.",
    "In 2010, IKEA switched its catalog font from Futura to Verdana, causing controversy among typography enthusiasts.",
    "The typeface Wingdings, a set of symbols and icons, was created by Charles Bigelow and Kris Holmes in 1990.",
    "The weight of a font refers to its thickness, ranging from thin to black.",
    "The font size 'em' is relative to the current font size and can be used to create responsive designs.",
    "The Romain du Roi typeface, commissioned by Louis XIV in 1692, was one of the first typefaces designed using a grid system.",
    "Dyslexic-friendly fonts, such as Open Dyslexie and Lexend, are designed to improve readability for individuals with dyslexia.",
    "Ligatures are specially designed character combinations, such as 'fi' and 'fl', that improve the visual flow of text.",
    "Typefaces designed for screen use, like Verdana and Georgia, prioritize legibility on digital displays.",
    "The font industry has its own awards, such as the Type Directors Club Typeface Design Competition and the European Design Awards.",
    "The term 'typeface' refers to the overall design of a font, while 'font' refers to a specific style or weight within that typeface.",
    "Blackletter fonts, characterized by their ornate and calligraphic style, were popular in medieval Europe.",
    "The famous 'I ♥ NY' logo, designed by Milton Glaser in 1977, uses the American Typewriter font.",
    "The Google Fonts library offers over 1,000 free, open-source fonts for use in digital and print projects.",
    "The 'Bleeding Cowboy' font, known for its grungy, distressed appearance, gained popularity in the mid-2000s.",
    "The world's smallest legible font, designed by German artist Peter Wiegel, is only 1.25 points in size.",
    "The font 'Zapfino,' designed by Hermann Zapf, emulates elegant calligraphy and is often used for invitations and formal documents.",
    "Font licensing determines how a font can be used and distributed, with options such as desktop, web, and app licenses.",
    "The font 'Papyrus,' designed by Chris Costello in 1982, is often associated with a hand-drawn, ancient appearance.",
    "The font 'Arial,' created in 1982 by Robin Nicholas and Patricia Saunders, is often compared to Helvetica due to their similar design.",
    "The use of contrasting fonts in a design can create hierarchy and improve readability.",
    "In 2018, the US government released its own open-source typeface, 'Public Sans,' for use in official digital documents.",
    "The typeface 'Courier,' designed in 1955 by Howard 'Bud' Kettler, is a monospaced font that emulates the appearance of a typewriter.",
    "The Braille system, developed in the early 19th century, is a tactile font that enables the visually impaired to read through touch.",
    "The first commercial emoji font was developed by Shigetaka Kurita in 1999 for a Japanese mobile carrier.",
]
